monzo_profile:
  outputs:
    dev:
      dataset: dbt_dev_jbalfe
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: "{{ env_var('BIGQUERY_LOCATION') }}"
      method: oauth
      priority: interactive
      project: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
      threads: 4
      type: bigquery
  target: dev